### ISSUE TITLE
Playlists have items field nested under track key in JSON

### ISSUE THREAD

**Issue by kcomas** [deepakg/spotify#1]
eg for: https://open.spotify.com/user/xbagon/playlist/6HEB65u7x26jD04gkN6IJ4?si=jECarpoLT0KlIatG_u5GKA

The items key is found under the track key in the JSON response

I will submit a pr that fixes this

**Comment by deepakg** [comment]
Sorry it took me so long to get to this. My Github notification settings were mis-configured and I didn't see this issue and the accompanying pull request at all.
